export default {
    type: "champion",
    format: "standAloneComplex",
    version: "6.24.1",
    data: {
      Jinx: {
        version: "6.24.1",
        id: "Jinx",
        key: "222",
        name: "Jinx",
        title: "the Loose Cannon",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jinx.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg",
        blurb:
          "Jinx lives to wreak havoc without a thought for the consequences, leaving a trail of mayhem and panic in her wake. A manic and impulsive criminal, she despises nothing more than boredom, and gleefully brings her own volatile brand of pandemonium to ...",
        info: {
          attack: 9,
          defense: 2,
          magic: 4,
          difficulty: 6,
        },
        image: {
          full: "Jinx.png",
          sprite: "champion1.png",
          group: "champion",
          x: 192,
          y: 48,
          w: 48,
          h: 48,
        },
        tags: ["Marksman"],
      },
  
      Darius: {
        version: "6.24.1",
        id: "Darius",
        key: "122",
        name: "Darius",
        title: "the Hand of Noxus",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Darius.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_0.jpg",
        blurb:
          "There is no greater symbol of Noxian might than Darius, the nation's most feared and battle-hardened warrior. Orphaned at a young age, Darius had to fight to keep himself and his younger brother alive. By the time he joined the military, he had ...",
        info: {
          attack: 9,
          defense: 5,
          magic: 1,
          difficulty: 2,
        },
        image: {
          full: "Darius.png",
          sprite: "champion0.png",
          group: "champion",
          x: 384,
          y: 48,
          w: 48,
          h: 48,
        },
        tags: ["Fighter", "Tank"],
        partype: "MP",
        stats: {
          hp: 582.24,
          hpperlevel: 100,
          mp: 263,
          mpperlevel: 37.5,
          movespeed: 340,
          armor: 30,
          armorperlevel: 4,
          spellblock: 32.1,
          spellblockperlevel: 1.25,
          attackrange: 175,
          hpregen: 9.845,
          hpregenperlevel: 0.95,
          mpregen: 6.585,
          mpregenperlevel: 0.35,
          crit: 0,
          critperlevel: 0,
          attackdamage: 56,
          attackdamageperlevel: 5,
          attackspeedoffset: 0,
          attackspeedperlevel: 1,
        },
      },
  
      Morgana: {
        version: "6.24.1",
        id: "Morgana",
        key: "25",
        name: "Morgana",
        title: "Fallen Angel",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Morgana.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg",
        blurb:
          "There is a world far away populated by graceful and beautiful winged beings gifted with immortality, where an ancient conflict still rages. Like so many conflicts, this war split families. One side proclaimed themselves as beings of perfect order and ...",
        info: {
          attack: 1,
          defense: 6,
          magic: 8,
          difficulty: 1,
        },
        image: {
          full: "Morgana.png",
          sprite: "champion2.png",
          group: "champion",
          x: 432,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Mage", "Support"],
        partype: "MP",
        stats: {
          hp: 547.48,
          hpperlevel: 86,
          mp: 340.8,
          mpperlevel: 60,
          movespeed: 335,
          armor: 25.384,
          armorperlevel: 3.8,
          spellblock: 30,
          spellblockperlevel: 0,
          attackrange: 450,
          hpregen: 5.705,
          hpregenperlevel: 0.6,
          mpregen: 8.5,
          mpregenperlevel: 0.8,
          crit: 0,
          critperlevel: 0,
          attackdamage: 55.46,
          attackdamageperlevel: 3.5,
          attackspeedoffset: 0,
          attackspeedperlevel: 1.53,
        },
      },
  
      Irelia: {
        version: "6.24.1",
        id: "Irelia",
        key: "39",
        name: "Irelia",
        title: "the Will of the Blades",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Irelia.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Irelia_0.jpg",
        blurb:
          "''The sword flourishes, as though painting with blood.''<br><br>The Ionians have developed some of the most breathtaking and deadly martial arts in all of Runeterra - just one manifestation of their pursuit of enlightenment. The most remarkable blade ...",
        info: {
          attack: 7,
          defense: 4,
          magic: 5,
          difficulty: 5,
        },
        image: {
          full: "Irelia.png",
          sprite: "champion1.png",
          group: "champion",
          x: 384,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Fighter", "Assassin"],
        partype: "MP",
        stats: {
          hp: 607.2,
          hpperlevel: 90,
          mp: 338.8,
          mpperlevel: 32,
          movespeed: 345,
          armor: 25.3,
          armorperlevel: 3.75,
          spellblock: 32.1,
          spellblockperlevel: 1.25,
          attackrange: 125,
          hpregen: 8.59,
          hpregenperlevel: 0.65,
          mpregen: 8.1,
          mpregenperlevel: 0.65,
          crit: 0,
          critperlevel: 0,
          attackdamage: 61.544,
          attackdamageperlevel: 3.3,
          attackspeedoffset: -0.06,
          attackspeedperlevel: 3.2,
        },
      },
  
      Lux: {
        version: "6.24.1",
        id: "Lux",
        key: "99",
        name: "Lux",
        title: "the Lady of Luminosity",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lux.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg",
        blurb:
          "Born to the prestigious Crownguards, the paragon family of Demacian service, Luxanna was destined for greatness. She grew up as the family's only daughter, and she immediately took to the advanced education and lavish parties required of families as ...",
        info: {
          attack: 2,
          defense: 4,
          magic: 9,
          difficulty: 5,
        },
        image: {
          full: "Lux.png",
          sprite: "champion2.png",
          group: "champion",
          x: 48,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Mage", "Support"],
        partype: "MP",
        stats: {
          hp: 477.72,
          hpperlevel: 79,
          mp: 384,
          mpperlevel: 47,
          movespeed: 330,
          armor: 18.72,
          armorperlevel: 4,
          spellblock: 30,
          spellblockperlevel: 0,
          attackrange: 550,
          hpregen: 5.42,
          hpregenperlevel: 0.55,
          mpregen: 6,
          mpregenperlevel: 0.8,
          crit: 0,
          critperlevel: 0,
          attackdamage: 53.544,
          attackdamageperlevel: 3.3,
          attackspeedoffset: 0,
          attackspeedperlevel: 1.36,
        },
      },
  
      Akali: {
        version: "6.24.1",
        id: "Akali",
        key: "84",
        name: "Akali",
        title: "the Fist of Shadow",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Akali.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg",
        blurb:
          "There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...",
        info: {
          attack: 5,
          defense: 3,
          magic: 8,
          difficulty: 7,
        },
        image: {
          full: "Akali.png",
          sprite: "champion0.png",
          group: "champion",
          x: 96,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Assassin"],
        partype: "Energy",
        stats: {
          hp: 587.8,
          hpperlevel: 85,
          mp: 200,
          mpperlevel: 0,
          movespeed: 350,
          armor: 26.38,
          armorperlevel: 3.5,
          spellblock: 32.1,
          spellblockperlevel: 1.25,
          attackrange: 125,
          hpregen: 8.34,
          hpregenperlevel: 0.65,
          mpregen: 50,
          mpregenperlevel: 0,
          crit: 0,
          critperlevel: 0,
          attackdamage: 58.376,
          attackdamageperlevel: 3.2,
          attackspeedoffset: -0.1,
          attackspeedperlevel: 3.1,
        },
      },
  
      Gangplank: {
        version: "6.24.1",
        id: "Gangplank",
        key: "41",
        name: "Gangplank",
        title: "the Saltwater Scourge",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Gangplank.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gangplank_0.jpg",
        blurb:
          "''I was cutting throats and sinking Noxian war galleys when you were still pissing your britches, boy. You don't want to take me on.''<br><br>As unpredictable as he is brutal, the dethroned reaver king known as Gangplank is feared far and wide. Where ...",
        info: {
          attack: 7,
          defense: 6,
          magic: 4,
          difficulty: 9,
        },
        image: {
          full: "Gangplank.png",
          sprite: "champion1.png",
          group: "champion",
          x: 0,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Fighter"],
        partype: "MP",
        stats: {
          hp: 540,
          hpperlevel: 82,
          mp: 282,
          mpperlevel: 40,
          movespeed: 345,
          armor: 26,
          armorperlevel: 3,
          spellblock: 32.1,
          spellblockperlevel: 1.25,
          attackrange: 125,
          hpregen: 6,
          hpregenperlevel: 0.6,
          mpregen: 7.5,
          mpregenperlevel: 0.7,
          crit: 0,
          critperlevel: 0,
          attackdamage: 56,
          attackdamageperlevel: 3,
          attackspeedoffset: 0,
          attackspeedperlevel: 3.2,
        },
      },
  
      Garen: {
        version: "6.24.1",
        id: "Garen",
        key: "86",
        name: "Garen",
        title: "The Might of Demacia",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Garen.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_0.jpg",
        blurb:
          "Throughout Valoran, the resolve of Demacia's military is alternately celebrated or despised, but always respected. Their ''zero tolerance'' moral code is strictly upheld by civilians and soldiers alike. In combat, this means Demacian troops may not ...",
        info: {
          attack: 7,
          defense: 7,
          magic: 1,
          difficulty: 5,
        },
        image: {
          full: "Garen.png",
          sprite: "champion1.png",
          group: "champion",
          x: 48,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Fighter", "Tank"],
        partype: "None",
        stats: {
          hp: 616.28,
          hpperlevel: 84.25,
          mp: 0,
          mpperlevel: 0,
          movespeed: 340,
          armor: 27.536,
          armorperlevel: 3,
          spellblock: 32.1,
          spellblockperlevel: 1.25,
          attackrange: 175,
          hpregen: 7.84,
          hpregenperlevel: 0.5,
          mpregen: 0,
          mpregenperlevel: 0,
          crit: 0,
          critperlevel: 0,
          attackdamage: 57.88,
          attackdamageperlevel: 4.5,
          attackspeedoffset: 0,
          attackspeedperlevel: 2.9,
        },
      },
  
      Jhin: {
        version: "6.24.1",
        id: "Jhin",
        key: "202",
        name: "Jhin",
        title: "the Virtuoso",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jhin.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jhin_0.jpg",
        blurb:
          "''Art requires a certain...cruelty.''<br><br>Jhin is a meticulous criminal psychopath who believes murder is art. Once an Ionian prisoner, but freed by shadowy elements within Ionia's ruling council, the serial killer now works as their cabal's ...",
        info: {
          attack: 10,
          defense: 2,
          magic: 6,
          difficulty: 6,
        },
        image: {
          full: "Jhin.png",
          sprite: "champion1.png",
          group: "champion",
          x: 144,
          y: 48,
          w: 48,
          h: 48,
        },
        tags: ["Marksman", "Assassin"],
        partype: "MP",
        stats: {
          hp: 540,
          hpperlevel: 85,
          mp: 300,
          mpperlevel: 50,
          movespeed: 330,
          armor: 20,
          armorperlevel: 3.5,
          spellblock: 30,
          spellblockperlevel: 0,
          attackrange: 550,
          hpregen: 6,
          hpregenperlevel: 0.55,
          mpregen: 6,
          mpregenperlevel: 0.8,
          crit: 0,
          critperlevel: 0,
          attackdamage: 53,
          attackdamageperlevel: 4,
          attackspeedoffset: 0,
          attackspeedperlevel: 0,
        },
      },
  
      Amumu: {
        version: "6.24.1",
        id: "Amumu",
        key: "32",
        name: "Amumu",
        title: "the Sad Mummy",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Amumu.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg",
        blurb:
          "''Solitude can be lonelier than death.''<br><br>A lonely and melancholy soul from ancient Shurima, Amumu roams the world in search of a friend. Cursed by an ancient spell, he is doomed to remain alone forever, as his touch is death and his affection ...",
        info: {
          attack: 2,
          defense: 6,
          magic: 8,
          difficulty: 3,
        },
        image: {
          full: "Amumu.png",
          sprite: "champion0.png",
          group: "champion",
          x: 192,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Tank", "Mage"],
        partype: "MP",
        stats: {
          hp: 613.12,
          hpperlevel: 84,
          mp: 287.2,
          mpperlevel: 40,
          movespeed: 335,
          armor: 23.544,
          armorperlevel: 3.8,
          spellblock: 32.1,
          spellblockperlevel: 1.25,
          attackrange: 125,
          hpregen: 8.875,
          hpregenperlevel: 0.85,
          mpregen: 7.38,
          mpregenperlevel: 0.525,
          crit: 0,
          critperlevel: 0,
          attackdamage: 53.384,
          attackdamageperlevel: 3.8,
          attackspeedoffset: -0.02,
          attackspeedperlevel: 2.18,
        },
      },
  
      Ahri: {
        version: "6.24.1",
        id: "Ahri",
        key: "103",
        name: "Ahri",
        title: "the Nine-Tailed Fox",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ahri.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg",
        blurb:
          "Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...",
        info: {
          attack: 3,
          defense: 4,
          magic: 8,
          difficulty: 5,
        },
        image: {
          full: "Ahri.png",
          sprite: "champion0.png",
          group: "champion",
          x: 48,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Mage", "Assassin"],
        partype: "MP",
        stats: {
          hp: 514.4,
          hpperlevel: 80,
          mp: 334,
          mpperlevel: 50,
          movespeed: 330,
          armor: 20.88,
          armorperlevel: 3.5,
          spellblock: 30,
          spellblockperlevel: 0,
          attackrange: 550,
          hpregen: 6.505,
          hpregenperlevel: 0.6,
          mpregen: 6,
          mpregenperlevel: 0.8,
          crit: 0,
          critperlevel: 0,
          attackdamage: 53.04,
          attackdamageperlevel: 3,
          attackspeedoffset: -0.065,
          attackspeedperlevel: 2,
        },
      },
  
      Ryze: {
        version: "6.24.1",
        id: "Ryze",
        key: "13",
        name: "Ryze",
        title: "the Rune Mage",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ryze.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ryze_0.jpg",
        blurb:
          "''Take care with this world. What is made can be unmade.''<br><br>Widely considered one of the most adept sorcerers on Runeterra, Ryze is an ancient, hard-bitten archmage with an impossibly heavy burden to bear. Armed with a boundless constitution and ...",
        info: {
          attack: 2,
          defense: 2,
          magic: 10,
          difficulty: 7,
        },
        image: {
          full: "Ryze.png",
          sprite: "champion2.png",
          group: "champion",
          x: 336,
          y: 96,
          w: 48,
          h: 48,
        },
        tags: ["Mage", "Fighter"],
        partype: "MP",
        stats: {
          hp: 558.48,
          hpperlevel: 86,
          mp: 400,
          mpperlevel: 50,
          movespeed: 340,
          armor: 21.552,
          armorperlevel: 3,
          spellblock: 30,
          spellblockperlevel: 0,
          attackrange: 550,
          hpregen: 7,
          hpregenperlevel: 0.55,
          mpregen: 6,
          mpregenperlevel: 0.8,
          crit: 0,
          critperlevel: 0,
          attackdamage: 55.04,
          attackdamageperlevel: 3,
          attackspeedoffset: 0,
          attackspeedperlevel: 2.112,
        },
      },
  
      Khazix: {
        version: "6.24.1",
        id: "Khazix",
        key: "121",
        name: "Kha'Zix",
        title: "the Voidreaver",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Khazix.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_0.jpg",
        blurb:
          "A vicious Void predator, Kha'Zix infiltrated Valoran to devour the land's most promising creatures. With each kill he absorbs his prey's strength, evolving to grow more powerful. Kha'Zix hungers most to conquer and consume Rengar, the one beast he ...",
        info: {
          attack: 9,
          defense: 4,
          magic: 3,
          difficulty: 6,
        },
        image: {
          full: "Khazix.png",
          sprite: "champion1.png",
          group: "champion",
          x: 96,
          y: 96,
          w: 48,
          h: 48,
        },
        tags: ["Assassin", "Fighter"],
        partype: "MP",
        stats: {
          hp: 572.8,
          hpperlevel: 85,
          mp: 327.2,
          mpperlevel: 40,
          movespeed: 350,
          armor: 27,
          armorperlevel: 3,
          spellblock: 32.1,
          spellblockperlevel: 1.25,
          attackrange: 125,
          hpregen: 7.51,
          hpregenperlevel: 0.75,
          mpregen: 7.59,
          mpregenperlevel: 0.5,
          crit: 0,
          critperlevel: 0,
          attackdamage: 55.21,
          attackdamageperlevel: 3.1,
          attackspeedoffset: -0.065,
          attackspeedperlevel: 2.7,
        },
      },
  
      Nautilus: {
        version: "6.24.1",
        id: "Nautilus",
        key: "111",
        name: "Nautilus",
        title: "the Titan of the Depths",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nautilus.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nautilus_0.jpg",
        blurb:
          "Once, Nautilus was a sailor commissioned by the Institute of War to explore the uncharted reaches of the Guardian's Sea. This expedition took him deep into unknown waters where he and his crew found a vast section of black oozing liquid that none of ...",
        info: {
          attack: 4,
          defense: 6,
          magic: 6,
          difficulty: 6,
        },
        image: {
          full: "Nautilus.png",
          sprite: "champion2.png",
          group: "champion",
          x: 96,
          y: 48,
          w: 48,
          h: 48,
        },
        tags: ["Tank", "Fighter"],
        partype: "MP",
        stats: {
          hp: 576.48,
          hpperlevel: 86,
          mp: 334,
          mpperlevel: 47,
          movespeed: 325,
          armor: 26.46,
          armorperlevel: 3.75,
          spellblock: 32.1,
          spellblockperlevel: 1.25,
          attackrange: 175,
          hpregen: 8.37,
          hpregenperlevel: 0.55,
          mpregen: 8.625,
          mpregenperlevel: 0.7,
          crit: 0,
          critperlevel: 0,
          attackdamage: 57.544,
          attackdamageperlevel: 3.3,
          attackspeedoffset: 0.02,
          attackspeedperlevel: 1,
        },
      },
  
      Lulu: {
        version: "6.24.1",
        id: "Lulu",
        key: "117",
        name: "Lulu",
        title: "the Fae Sorceress",
        img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lulu.png",
        splash:
          "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_0.jpg",
        blurb:
          "Perhaps more than any other champion in the League, Lulu marches to the beat of her own drum. During her youth in Bandle City, she spent most of her time wandering alone in the forest or lost in a daydream. It wasn't that she was antisocial; the ...",
        info: {
          attack: 4,
          defense: 5,
          magic: 7,
          difficulty: 5,
        },
        image: {
          full: "Lulu.png",
          sprite: "champion2.png",
          group: "champion",
          x: 0,
          y: 0,
          w: 48,
          h: 48,
        },
        tags: ["Support", "Mage"],
        partype: "MP",
        stats: {
          hp: 552.76,
          hpperlevel: 74,
          mp: 350,
          mpperlevel: 55,
          movespeed: 330,
          armor: 19.216,
          armorperlevel: 3.7,
          spellblock: 30,
          spellblockperlevel: 0,
          attackrange: 550,
          hpregen: 6.005,
          hpregenperlevel: 0.6,
          mpregen: 11,
          mpregenperlevel: 0.6,
          crit: 0,
          critperlevel: 0,
          attackdamage: 46.368,
          attackdamageperlevel: 2.6,
          attackspeedoffset: 0,
          attackspeedperlevel: 2.25,
        },
      },
    },
  };
  